Replace Template provider with template_file func
ministryofjustice/modernisation-platform-terraform-ecs pull request #58
Opened 2023-02-15 16:20 UTC by georgepstaylor

2023-02-16 13:26 UTC, kylehodgetts requested changes

2023-02-16 13:26 UTC, kylehodgetts commented on README.md
> +  task_definition          = templatefile("templates/task_definition.json")
```suggestion
  task_definition          = templatefile("templates/task_definition.json", {})
```

2023-02-16 13:26 UTC, kylehodgetts commented on test/unit-test/main.tf
> +}
```suggestion
}

```

2023-02-16 13:35 UTC, kylehodgetts approved these changes

2025-01-10 10:35 UTC, ASTRobinson commented
as per slack request https://mojdt.slack.com/archives/C01A7QK5VM1/p1736505092811219

2025-01-10 10:35 UTC, closed without merging